spring.application.name=backendintro
server.port=8081
spring.output.ansi.enabled=ALWAYS

##########################################################
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=BackendIntroDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=sapass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
##########################################################